### ISSUE TITLE
Please add list of Demos by the community.

### ISSUE THREAD

**Issue by ucalyptus** [googlemaps/deck.gl-demos#7]
deck.gl + Google Maps has been a hit so far.
**Suggesting adding demos by community**

**Example**
[Plotting Storms in the United States 2019 using deck.gl and Google Maps Javascript API](https://ucalyptus.github.io/PlotMaps/)

**Comment by jpoehnelt** [comment]
@amuramoto thoughts?

**Comment by amuramoto** [comment]
cool idea!

@ucalyptus got any other examples from yourself or others in the community? We'd probably want at least a few before adding

**Comment by ucalyptus** [comment]
> cool idea!
> 
> @ucalyptus got any other examples from yourself or others in the community? We'd probably want at least a few before adding

no other as far as I know. will keep checking .
